services:
  - type: web
    name: prpg-wjp-bridge-fe
    runtime: static
    buildCommand: yarn install && yarn build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
